### ISSUE TITLE
Cannot run server

### ISSUE THREAD

**Issue by biocide69** [lare96/asteria-2.0#108]
Exception in thread "main" java.lang.VerifyError: Bad type on operand stack
Exception Details:
  Location:
    com/asteria/world/item/ItemContainer.lambda$10(Lcom/asteria/world/item/Item;Ljava/lang/Object;)Z @1: invokevirtual
  Reason:
    Type 'java/lang/Object' (current frame, stack[0]) is not assignable to 'com/asteria/world/item/Item'
  Current Frame:
    bci: @1
    flags: { }
    locals: { 'com/asteria/world/item/Item', 'java/lang/Object' }
    stack: { 'java/lang/Object' }
  Bytecode:
    0x0000000: 2bb6 0032 2ab6 0032 a000 122b b600 352a
    0x0000010: b600 35a1 0007 04a7 0004 03ac          
  Stackmap Table:
    same_frame(@26)
    same_locals_1_stack_item_frame(@27,Integer)

	at com.asteria.world.shop.Shop.<init>(Shop.java:38)
	at com.asteria.world.shop.Shop$1.load(Shop.java:469)
	at com.asteria.util.JsonLoader.load(JsonLoader.java:54)
	at com.asteria.Main.main(Main.java:70)

Tried bringing this to attention on R-S thread but continuously ignored.

**Comment by lare96** [comment]
Finally there's a reason for this occurance, a quote from Ryley on this thread http://www.rune-server.org/runescape-development/rs2-server/downloads/551082-asteria-2-0-a-50.html#post4782781

"There is nothing wrong with your lambda expression; it's a bug with the Eclipse compiler that do not have native Java 8 support. Initially when I started developing a tad with you I had the same issue.

I filed an issue on the Eclipse bug tracker site and gave them reproducible test code, iirc it was fixed all you have to do is update your Java 8 support or get the latest version of Eclipse (recommended)"
