### ISSUE TITLE
Npcs after death issue

### ISSUE THREAD

**Issue by amarsut** [lare96/asteria-2.0#109]
Walking is not being called from here Npc.java upon respawn. Npcs don't walk after death.

public Npc(int npcId, Position position) {
  this.npcId = npcId;
  this.originalPosition = position.clone();
  this.maxHealth = getDefinition().getHitpoints();
  this.currentHealth = maxHealth;
  this.getPosition().setAs(originalPosition);
  this.setAutoRetaliate(true);

  if (this.getDefinition().isAggressive()) {
   NpcAggression.getAggressive().put(this, originalPosition);
  }
 }

**Comment by lare96** [comment]
Thank you! This will be fixed :)

**Comment by lare96** [comment]
Fixed in 3.0 :)
