### ISSUE TITLE
X-Log

### ISSUE THREAD

**Issue by PB-Daniel** [lare96/asteria-2.0#110]
If a player is in combat they are not allowed to x log, they are suppose to be logged in until they are out of combat.

**Comment by PB-Daniel** [comment]
Having more than 3 players in same region makes client spam with t2 mismatches.

**Comment by lare96** [comment]
Going to fix this today.

**Comment by lare96** [comment]
Fixed with commit https://github.com/lare96/asteria-3.0/commit/d6c4cd281f0925d3ac6e1e95a8859a565e6977a2
