### ISSUE TITLE
Bonuses not resetting on death

### ISSUE THREAD

**Issue by Loodie** [lare96/asteria-2.0#114]
Upon death, you lose all your items. Let's say im using a whip to attack an NPC, when I die, it goes on the ground like it belongs. And I no longer have it/see it. If I attack the NPC, It does the whip animation and I still have the bonuses of the whip and all the gear bonus I was wearing from when I died.

**Comment by Fridder** [comment]
PlayerDeath postdeath, you need to call these to update the player's info
		entity.writeBonus();
		entity.setFightType(FightType.UNARMED_PUNCH);

**Comment by lare96** [comment]
Fixed https://github.com/lare96/asteria-3.0/commit/e343cc6d8ddfee4a79c57351fbad5b93deaf2e54
